import { Review, ReviewSummary } from "./testimonials-types";

export const MOCK_SUMMARY: ReviewSummary = {
  overallRating: 5.0,
  totalReviews: 388,
  starDistribution: {
    5: 382,
    4: 6,
    3: 0,
    2: 0,
    1: 0,
  },
};

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    author: "Sarah J.",
    initials: "SJ",
    date: "2024-03-15",
    rating: 5,
    service: "Holistic Massage",
    text: "Absolutely incredible experience. The attention to detail and care provided was unmatched. I walked out feeling like a completely new person. Highly recommend for anyone looking to de-stress and heal.",
    verified: true,
  },
  {
    id: "r2",
    author: "Michael T.",
    initials: "MT",
    date: "2024-03-10",
    rating: 5,
    service: "Deep Tissue",
    text: "Best deep tissue massage I've had in years. The therapist really understood where my tension was and worked through it patiently. The atmosphere is also very calming and clean.",
    verified: true,
  },
  {
    id: "r3",
    author: "Emma W.",
    initials: "EW",
    date: "2024-03-05",
    rating: 5,
    service: "Reiki Healing",
    text: "A truly transformative session. I felt a significant shift in my energy and a deep sense of peace afterwards. The practitioner is gifted and very professional.",
    verified: true,
  },
  {
    id: "r4",
    author: "David L.",
    initials: "DL",
    date: "2024-02-28",
    rating: 5,
    service: "Sports Massage",
    text: "Great for recovery. I've been training for a marathon and this session helped loosen up tight muscles I didn't even know I had. promoting better movement.",
    verified: true,
  },
  {
    id: "r5",
    author: "Jessica P.",
    initials: "JP",
    date: "2024-02-20",
    rating: 5,
    service: "Aromatherapy",
    text: "The scents used were divine and the massage was so relaxing. It was the perfect escape from a busy week. I will definitely be booking again soon.",
    verified: true,
  },
  {
    id: "r6",
    author: "Robert K.",
    initials: "RK",
    date: "2024-02-15",
    rating: 4,
    service: "Integrated Healing",
    text: "Very good session, professional and effective. The environment was peaceful. Just wish availability was a bit better for weekends, but worth the wait.",
    verified: true,
  },
  {
    id: "r7",
    author: "Amanda B.",
    initials: "AB",
    date: "2024-02-10",
    rating: 5,
    service: "Holistic Massage",
    text: "Consistently excellent. I've been coming here for months and every session is tailored to exactly what I need that day. The therapists are true experts.",
    verified: true,
  },
  {
    id: "r8",
    author: "James H.",
    initials: "JH",
    date: "2024-02-05",
    rating: 5,
    service: "Deep Tissue",
    text: "Fixed my shoulder pain in just one session. I was skeptical but the results speak for themselves. Very knowledgeable staff who explain what they are doing.",
    verified: true,
  },
  {
    id: "r9",
    author: "Sophie M.",
    initials: "SM",
    date: "2024-01-30",
    rating: 5,
    service: "Reflexology",
    text: "Wonderful reflexology treatment. My feet felt amazing and my whole body felt balanced afterwards. Such a treat!",
    verified: true,
  },
  {
    id: "r10",
    author: "Daniel C.",
    initials: "DC",
    date: "2024-01-25",
    rating: 5,
    service: "Energy Work",
    text: "I didn't know what to expect but this was a powerful experience. Highly recommended for those open to alternative healing methods.",
    verified: true,
  },
  {
    id: "r11",
    author: "Olivia R.",
    initials: "OR",
    date: "2024-01-20",
    rating: 5,
    service: "Holistic Massage",
    text: "Simply the best. From the moment you walk in, you feel taken care of. The massage itself was perfect pressure and flow.",
    verified: true,
  },
  {
    id: "r12",
    author: "Thomas G.",
    initials: "TG",
    date: "2024-01-15",
    rating: 4,
    service: "Sports Massage",
    text: "Solid sports massage. Helped with my hamstring tightness. Good facility and friendly staff.",
    verified: true,
  },
  {
    id: "r13",
    author: "Rachel N.",
    initials: "RN",
    date: "2024-01-10",
    rating: 5,
    service: "Pregnancy Massage",
    text: "Saved my back during my third trimester! So grateful for the care and expertise. It made a huge difference in my comfort levels.",
    verified: true,
  },
  {
    id: "r14",
    author: "Kevin S.",
    initials: "KS",
    date: "2024-01-05",
    rating: 5,
    service: "Deep Tissue",
    text: "Intense but exactly what was needed. Not a fluffy spa massage, this is real therapeutic work. Highly effective.",
    verified: true,
  },
  {
    id: "r15",
    author: "Laura D.",
    initials: "LD",
    date: "2023-12-28",
    rating: 5,
    service: "Holistic Facial",
    text: "My skin is glowing! The products used felt so natural and high quality. The facial massage was an added bonus I didn't expect.",
    verified: true,
  },
  {
    id: "r16",
    author: "Mark P.",
    initials: "MP",
    date: "2023-12-20",
    rating: 5,
    service: "Integrated Healing",
    text: "A unique blend of modalities that works wonders. I always leave feeling lighter and more grounded.",
    verified: true,
  },
  {
    id: "r17",
    author: "Jennifer A.",
    initials: "JA",
    date: "2023-12-15",
    rating: 5,
    service: "Reiki",
    text: "Beautiful energy and a safe space. I felt very supported throughout the session. Will be back for sure.",
    verified: true,
  },
  {
    id: "r18",
    author: "Brian F.",
    initials: "BF",
    date: "2023-12-10",
    rating: 5,
    service: "Massage",
    text: "Top notch service. Easy booking, great location, and fantastic massage. Can't ask for more.",
    verified: true,
  },
  {
    id: "r19",
    author: "Michelle V.",
    initials: "MV",
    date: "2023-12-05",
    rating: 5,
    service: "Aromatherapy",
    text: "Heavenly. The essential oil blend created for me was perfect. I slept like a baby that night.",
    verified: true,
  },
  {
    id: "r20",
    author: "Chris B.",
    initials: "CB",
    date: "2023-11-30",
    rating: 5,
    service: "Deep Tissue",
    text: "Very skilled therapist. Found trigger points I didn't know existed and released them. Pain free for the first time in weeks.",
    verified: true,
  },
   {
    id: "r21",
    author: "Nina R.",
    initials: "NR",
    date: "2023-11-25",
    rating: 5,
    service: "Holistic Massage",
    text: "I booked this as a gift to myself and it was the best decision. Complete relaxation and rejuvenation.",
    verified: true,
  },
];
